#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# First package managers
# Install homebrew
homebrew/install.sh 2>&1

# Run Homebrew through the Brewfile
while true; do
  read -p "Do you wish to install brew packages (need to be Thierry Michel… ;)? [Y/n]" yn
  case $yn in
    [Yy]* ) echo "› brew bundle"; brew bundle; break;;
    [Nn]* ) echo "› skip brew bundle"; break;;
    * ) echo "Please answer yes or no.";;
  esac
done

# Second OS related stuff
# Set macOS defaults
echo "› Mac OS defaults"
macos/defaults.sh

# Third, ZSH
echo "› Installing Antigen"
curl -L git.io/antigen > ~/antigen.zsh
echo "› Set ZSH as default"
ZSH_PATH=$(which zsh)
if ! grep -q $ZSH_PATH '/etc/shells'; then
  echo $ZSH_PATH | sudo tee -a /etc/shells
fi
chsh -s $(which zsh)

echo "› installers"
# find the installers and run them iteratively
# find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

echo ''
echo '  All stuff installed!'
