#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "› nvm"
# Install nvm + latest
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash

# Install homebrew
homebrew/install.sh 2>&1

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# Set macOS defaults
echo "› Mac OS defaults"
macos/defaults.sh

echo "› installers"
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

echo "› Set ZSH as default"
chsh -s $(which zsh)

echo ''
echo '  All stuff installed!'
