#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# First package managers

# Install nvm + latest -> now ZSH plugin (via Antigen)
# echo "› nvm"
# echo "  Installing nvm for you."
# curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash

# Install homebrew
homebrew/install.sh 2>&1

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# Second OS related stuff
# Set macOS defaults
echo "› Mac OS defaults"
macos/defaults.sh

# Third, ZSH
echo "› Set ZSH as default"
chsh -s $(which zsh)

echo "› installers"
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

echo ''
echo '  All stuff installed!'
